FROM python:latest

#RUN apt update -y && \
#    apt install python
EXPOSE 80

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

#ENTRYPOINT [ "python" ]
#CMD [ "python", "-m blockchain 5000"]
CMD [ "python", "-m" , "blockchain", "80"]